version: '3'

services:

  web:
  
    build: .

    container_name: server

    ports:

      - "8082:80"

    volumes:

      - ./www:/var/www/html/

      - ./conf:/etc/apache2/
      

      

      
    links:
    
    - db


  db:

    image: mysql

    container_name: my_mysql

    environment:

      MYSQL_ROOT_PASSWORD: 12345

      MYSQL_DATABASE: news_db

      MYSQL_USER: user

      MYSQL_PASSWORD: qwerty

    ports:

      - "3306:3306"

    volumes:

      - ./data:/var/lib/mysql
      

      

  phpmyadmin:

    image: phpmyadmin

    container_name: pma


    environment:

      PMA_HOST: my_mysql

      PMA_PORT: 3306

      PMA_ARBITRARY: 1

    ports:

      - 8081:80
      
    depends_on: 
      - db

volumes:

  data:
  
  www:
  
  conf:
  
